name: Codecov

on: push

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
      - name: Install deps
        run: npm install nyc
        run: nyc npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
