name: Codecov

on: push

jobs:
  coverage:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: Upload coverage to Codecov
      - uses: actions/checkout@v2
      - run: npm run coverage
        uses: codecov/codecov-action@v1.0.7
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/cobertura-coverage.xml
          fail_ci_if_error: true
