name: Codecov

on: push

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.7
        with:
          name: codecov-umbrella
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/cobertura-coverage.xml
          fail_ci_if_error: true
